version: '2'
services:
  db:
    image: mysql:5.7
    ports:
    - "3306:3306"
    volumes:
    - /app/db_data:/var/lib/mysql:rw
    environment:
    - MYSQL_DATABASE:zerglings
    - MYSQL_USER:root
    - MYSQL_ROOT_PASSWORD:Kerrigan

  php:
    image: php
    ports:
    - "80:80"
    volumes:
    - /app/src:/var/www/html
    working_dir: /var/www/html
    links:
    - db:db
    environment:
    - MYSQL_DATABASE:zerglings
    - MYSQL_USER:root
    - MYSQL_ROOT_PASSWORD:Kerrigan

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
    - db:db
    ports:
    - 8081:80
