version: '2'
services:
  mc:
    image: itzg/minecraft-server
    ports:
    - "25565:25565"
    volumes:
    - /path/on/host:/data
    environment:
    - TYPE:FORGE
    - FORGEVERSION:10.13.4.1448
    - EULA:TRUE
